// Odoo 模块: link_tracker
// 由 odoo-parser.py + odoo2feida.js 自动生成
exports.models = [
  {
    "_name": "link.tracker",
    "_description": "Link Tracker",
    "_auto": true,
    "_fields": {
      "url": {
        "type": "char",
        "label": "Target URL",
        "required": true
      },
      "absolute_url": {
        "type": "char",
        "label": "Absolute URL"
      },
      "short_url": {
        "type": "char",
        "label": "Tracked URL"
      },
      "redirected_url": {
        "type": "char",
        "label": "Redirected URL"
      },
      "short_url_host": {
        "type": "char",
        "label": "Host of the short URL"
      },
      "title": {
        "type": "char",
        "label": "Page Title"
      },
      "label": {
        "type": "char",
        "label": "Button label"
      },
      "link_code_ids": {
        "type": "one2many",
        "label": "link.tracker.code"
      },
      "code": {
        "type": "char",
        "label": "Short URL code"
      },
      "link_click_ids": {
        "type": "one2many",
        "label": "link.tracker.click"
      },
      "count": {
        "type": "integer",
        "label": "Number of Clicks"
      },
      "campaign_id": {
        "type": "many2one",
        "label": "set null"
      },
      "medium_id": {
        "type": "many2one",
        "label": "set null"
      },
      "source_id": {
        "type": "many2one",
        "label": "set null"
      }
    }
  },
  {
    "_name": "link.tracker.code",
    "_description": "Link Tracker Code",
    "_auto": true,
    "_fields": {
      "code": {
        "type": "char",
        "label": "Short URL Code",
        "required": true
      },
      "link_id": {
        "type": "many2one",
        "label": "link.tracker",
        "required": true
      }
    }
  },
  {
    "_name": "link.tracker.click",
    "_description": "Link Tracker Click",
    "_auto": true,
    "_fields": {
      "campaign_id": {
        "type": "many2one",
        "label": "campaign_id"
      },
      "link_id": {
        "type": "many2one",
        "label": "link_id"
      },
      "ip": {
        "type": "char",
        "label": "Internet Protocol"
      },
      "country_id": {
        "type": "many2one",
        "label": "res.country"
      }
    }
  },
  {
    "_name": "utmcampaign",
    "_description": "UTM Campaign",
    "_auto": true,
    "_fields": {
      "click_count": {
        "type": "integer",
        "label": "Number of clicks generated by the campaign"
      }
    },
    "_inherit": "utm.campaign"
  }
];
